/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "primary-fixed": "#e5deff",
        "tertiary-container": "#008190",
        "secondary-fixed-dim": "#e9c400",
        "on-background": "#1c1c18",
        "primary": "#5b3cdd",
        "on-error-container": "#93000a",
        "error": "#ba1a1a",
        "surface-container-high": "#ebe8e2",
        "primary-fixed-dim": "#c9bfff",
        "surface-variant": "#e6e2dc",
        "on-tertiary": "#ffffff",
        "outline-variant": "#c9c4d8",
        "surface-tint": "#5d3fe0",
        "surface-dim": "#ddd9d4",
        "inverse-surface": "#31302d",
        "on-error": "#ffffff",
        "tertiary": "#006672",
        "on-secondary-fixed-variant": "#544600",
        "secondary-fixed": "#ffe16d",
        "background": "#fdf9f3",
        "secondary-container": "#fcd400",
        "surface-container": "#f1ede7",
        "outline": "#797587",
        "on-tertiary-fixed-variant": "#004f58",
        "surface-container-lowest": "#ffffff",
        "on-surface-variant": "#484555",
        "on-primary-fixed-variant": "#441cc8",
        "inverse-on-surface": "#f4f0ea",
        "on-primary-fixed": "#1a0063",
        "surface-container-low": "#f7f3ed",
        "surface-container-highest": "#e6e2dc",
        "on-secondary-container": "#6e5c00",
        "error-container": "#ffdad6",
        "surface": "#fdf9f3",
        "on-primary": "#ffffff",
        "on-secondary-fixed": "#221b00",
        "on-primary-container": "#fffbff",
        "surface-bright": "#fdf9f3",
        "on-surface": "#1c1c18",
        "on-secondary": "#ffffff",
        "inverse-primary": "#c9bfff",
        "on-tertiary-fixed": "#001f24",
        "tertiary-fixed-dim": "#00daf3",
        "secondary": "#705d00",
        "tertiary-fixed": "#9cf0ff",
        "primary-container": "#7459f7",
        "on-tertiary-container": "#f7feff",
      },
      borderRadius: {
        DEFAULT: "0px",
        lg: "0px",
        xl: "0px",
        full: "0px",
      },
      fontFamily: {
        headline: ["Space Grotesk", "sans-serif"],
        display: ["Space Grotesk", "sans-serif"],
        body: ["Newsreader", "serif"],
        label: ["Space Grotesk", "sans-serif"],
      },
      boxShadow: {
        "neobrutal": "6px 6px 0px 0px rgba(0,0,0,1)",
        "neobrutal-hover": "0px 0px 0px 0px rgba(0,0,0,1)",
      },
    },
  },
  plugins: [],
}
